apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i3jjm0ost-python 
  janus-idp.io/tekton: i3jjm0ost-python
  backstage.io/kubernetes-id: i3jjm0ost-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i3jjm0ost-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  