apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: i3jjm0ost-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i3jjm0ost-python 
  name: i3jjm0ost-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: i3jjm0ost-python
    weight: 100 
