apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i3jjm0ost-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i3jjm0ost-python 
  name: i3jjm0ost-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i3jjm0ost-python 
